title: 台語文記憶。Tâi-gí-bûn Kì-ek
email: taibunkesimi+taigibunki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tâi-gí-bûn Kì-ek, Tâi-bûn Ke-si Mī
logo: "/assets/images/logo.png"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

minimal_mistakes_skin: dark
search: true
atom_feed:
  hide: true
locale: "zh-TW"
date_format: "%Y"

# Outputting
permalink: /:year/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Taipei # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# markdown render engine.
markdown: kramdown
kramdown:
  typographic_symbols:
    ndash: --

author:
  name: "台語文記憶"
  avatar: "/assets/images/logo.png"
  bio: "Tâi-gí-bûn Kì-ek"
  links:
    - label: "Tâi-bûn Ke-si Mī 台文雞絲麵"
      icon: "fas fa-fw fa-link"
      url: "https://linktr.ee/taibunkesimi"

footer:
  links:
    - label: "Tâi-bûn Ke-si Mī 台文雞絲麵"
      icon: "fas fa-fw fa-link"
      url: "https://linktr.ee/taibunkesimi"

include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: false
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc_sticky: true

category_archive:
  type: liquid
  path: /hunlui/
tag_archive:
  type: liquid
  path: /phiaua/
